# DigitalOcean App Platform - SignalHire Callback Server
# This deploys the FastAPI callback server to receive SignalHire webhooks

name: signalhire-callback
region: nyc

services:
  - name: callback-server
    # Use the callback server code from signalhireagent (or this directory)
    github:
      repo: YOUR_GITHUB_USERNAME/signalhireagent
      branch: master
      deploy_on_push: true

    # Or use a Dockerfile
    dockerfile_path: Dockerfile

    http_port: 8000

    instance_count: 1
    instance_size_slug: basic-xxs

    # Environment variables
    envs:
      - key: SIGNALHIRE_API_KEY
        value: "202.R6cmAKCaf7FHPPstzfP2Vnh5XOBo"
        scope: RUN_TIME

      - key: HOST
        value: "0.0.0.0"
        scope: RUN_TIME

      - key: PORT
        value: "8000"
        scope: RUN_TIME

    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3

    # Routes
    routes:
      - path: /
      - path: /signalhire/callback
      - path: /health

# Alerts
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
