name: signalhire-callback
region: nyc
services:
  - name: callback
    source_dir: /
    dockerfile_path: Dockerfile.callback
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
    routes:
      - path: /
